version: '3.7'

services:

  mongo:
    container_name: practice_mongo
    image: mongo
    volumes:
      - practice_mongo_data:/data/mongo
    ports:
      - "27017:27017"

    env_file:
      - .env

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    restart: always

  postgres:
    container_name: practice_postgres
    image: postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    env_file:
      - .env

    ports:
      - "127.0.0.1:5433:5432"

    volumes:
      - practice_postgres_data:/data

    restart: always

  backend:
    container_name: practice_backend
    build: .

    env_file:
      - .env

    command: bash -c "alembic upgrade head && uvicorn app:app --reload --host 0.0.0.0 --port 8000"

    ports:
      - 8000:8000

    depends_on:
      - postgres
    volumes:
      - practice_backend_data:/backend_data

    restart: always




volumes:
  practice_mongo_data:
  practice_postgres_data:
  practice_backend_data: